"""Fixed user_public_id type

Revision ID: 990edb856d7a
Revises: a5251045e901
Create Date: 2021-07-26 12:12:59.530445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990edb856d7a'
down_revision = 'a5251045e901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'user_public_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_unique_constraint(None, 'articles', ['user_public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    op.alter_column('articles', 'user_public_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
