"""Fixed unique tag

Revision ID: bd61002ccf10
Revises: 990edb856d7a
Create Date: 2021-07-26 12:15:42.241300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd61002ccf10'
down_revision = '990edb856d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_user_public_id_key', 'articles', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('articles_user_public_id_key', 'articles', ['user_public_id'])
    # ### end Alembic commands ###
